### ISSUE TITLE
Research on AI-assisted software development 

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/llm-swarm#1]
Here are some products similar to the one we will be building:

- Devin: https://www.cognition-labs.com/introducing-devin
- AutoGen: https://github.com/microsoft/autogen
- CrewAI: https://github.com/joaomdmoura/crewai
  - https://www.youtube.com/watch?v=iJjSjmZnNlI&pp=ygUGY3Jld2Fp
  - https://www.youtube.com/watch?v=s-jYxgKMqRc&pp=ygUGY3Jld2Fp
  - https://www.youtube.com/watch?v=02cdCd43Ccc&pp=ygUGY3Jld2Fp
- ACE Framework: https://github.com/daveshap/ACE_Framework
- Hierarchical Autonomous Agent Swarm (HAAS): https://github.com/daveshap/OpenAI_Agent_Swarm

- Pythagora https://github.com/Pythagora-io/gpt-pilot
- SWE Agent https://swe-agent.com/
- Devika https://github.com/stitionai/devika  
- OpenDevin https://opendevin.github.io/OpenDevin/ 

[What are agent swarms? YT](https://www.youtube.com/watch?v=IqovGsaTro8)

Let's see what functionalities they offer and what limitations they have.  

The goal is to identify areas where NLP can be used more effectively to automate basic software development tasks.  This research will help us determine how to integrate NLP functionalities into the LLM Swarm framework."

If you have time check out this free course by Hugging Face about NLP: https://huggingface.co/learn/nlp-course

Summarize your findings in a Google Doc and paste the link here for review.

---
Actual hours worked:
TG: 
RM: 15
CO: 16
MS: 
TT:

**Comment by rhysmah** [comment]
** Resources added by Rhys. Will update periodically. **
