### ISSUE TITLE
Create as a VSCode Extension

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/llm-swarm#5]
- [x] #18
- [x] #19
- [ ] #20

Develop a user-friendly interface (UI) for LLM Swarm using TypeScript with a JS framework of your choosing (React, Vue, Svelte, Angular). 

This could be a web-based interface or a graphical user interface (GUI) for desktop applications.

I recommended looking into how you can incorporate the [Monaco Editor](https://microsoft.github.io/monaco-editor/) into the app if its going to be web-based. 

For Desktop apps, my thoughts are this will be the harder path. Look into [Electron](https://www.electronjs.org/) or [Tauri](https://tauri.app/).

**Comment by carcango** [comment]
- [ ] Create basic extension logic
- [ ] Code basic functionality for user flow 
- [ ] Adapt previous project to work in extension
